spring:
  config:
    import: nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}
  application:
    name: backend
  datasource:
    url: jdbc:mysql://localhost:3306/bookdb?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      config:
        server-addr: 10.75.80.67:8848
        file-extension: yaml
        namespace: public
        group: DEFAULT_GROUP
        username: admin
        password: admin
      discovery:
        metadata:
          management.context-path: /actuator  # 确保健康检查路径正确
        server-addr: 10.75.80.67:8848
        namespace: public
        group: DEFAULT_GROUP
        username: admin
        password: admin
logging:
  level:
    org:
      springframework: INFO
server:
  port: 28082